ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8000

jwt:
    audience: "my-audience"
    issuer: "http://localhost"
    realm: "my-realm"
    secret: ${SECRET}
